### ISSUE TITLE
Is this other mod the same thing?

### ISSUE THREAD

**Issue by SoopCanSam** [Dolphin2Point1/FadingFlashlights#1]
I am not a math nerd. I do not make mods and don't know anything, but is your mod the same thing or is it better than this one: https://thunderstore.io/c/lethal-company/p/blink9803/DimmingFlashlights/ ?

**Comment by Dolphin2Point1** [comment]
yes i guess but theres no config options, and it follows a completely linear pattern

choose whichever mod you want

**Comment by SoopCanSam** [comment]
Thank you. That's a good point. I will be using yours.
